import CoreML

// Target: iOS (watch only if model is small and supported)
actor InferenceManager {
    // Replace `MyModel` with your autogenerated Core ML model class
    // private let model = try! MyModel(configuration: .init())

    func predictPlaceholder() -> String {
        // TODO: implement real inference
        return "ok"
    }
}
